/* 
  This file was generated by KreMLin <https://github.com/FStarLang/kremlin>
  KreMLin invocation: krml -verify -skip-compilation -bundle WasmSupport ../Writer.fst -I ../
  F* version: b55bb590
  KreMLin version: 2f843633
 */

#include "kremlib.h"
#ifndef __FStar_H
#define __FStar_H

#include "Prims.h"


Prims_int FStar_UInt_max_int(Prims_int n);

Prims_int FStar_UInt_logand(Prims_pos n, Prims_int a, Prims_int b);

extern Prims_int FStar_UInt8_v(uint8_t x);

#define __FStar_H_DEFINED
#endif
