/* 
  This file was generated by KreMLin <https://github.com/FStarLang/kremlin>
  KreMLin invocation: krml -verify -d reachability -skip-linking -bundle WasmSupport ../Writer.fst -I ../
  F* version: b55bb590
  KreMLin version: 2f843633
 */

#include "kremlib.h"
#ifndef __Prims_H
#define __Prims_H




extern krml_checked_int_t Prims_op_Multiply(krml_checked_int_t x, krml_checked_int_t y);

extern krml_checked_int_t Prims_op_Division(krml_checked_int_t x, krml_checked_int_t y);

extern krml_checked_int_t Prims_op_Subtraction(krml_checked_int_t x, krml_checked_int_t y);

extern krml_checked_int_t Prims_op_Addition(krml_checked_int_t x, krml_checked_int_t y);

extern krml_checked_int_t Prims_op_Modulus(krml_checked_int_t x, krml_checked_int_t y);

extern bool Prims_op_GreaterThan(krml_checked_int_t x0, krml_checked_int_t x1);

extern krml_checked_int_t Prims_pow2(krml_checked_int_t x0);

#define __Prims_H_DEFINED
#endif
