/* 
  This file was generated by KreMLin <https://github.com/FStarLang/kremlin>
  KreMLin invocation: krml -verify -skip-compilation -bundle WasmSupport ../Writer.fst -I ../
  F* version: b55bb590
  KreMLin version: 2f843633
 */

#include "kremlib.h"
#ifndef __Reader_H
#define __Reader_H

#include "Ring.h"
#include "FStar.h"


typedef Ring_ringstruct__uint8_t Reader_ringstruct8;

typedef uint8_t Reader_message;

typedef uint8_t *Reader_datapointer;

Ring_ringstruct__uint8_t Reader_init(uint32_t s);

bool Ring_is_poppable__uint8_t(Ring_ringstruct__uint8_t r);

uint32_t Reader_read(Ring_ringstruct__uint8_t r);

#define __Reader_H_DEFINED
#endif
