/* 
  This file was generated by KreMLin <https://github.com/FStarLang/kremlin>
  KreMLin invocation: krml -verify -skip-linking -bundle WasmSupport ../Reader.fst -I ../
  F* version: b55bb590
  KreMLin version: 2f843633
 */

#include "kremlib.h"
#ifndef __Reader_H
#define __Reader_H

#include "Misc.h"
#include "Ring.h"


typedef Ring_ringstruct__uint8_t Reader_ringstruct8;

typedef uint8_t Reader_message;

typedef uint8_t *Reader_datapointer;

Ring_ringstruct__uint8_t Reader_init(uint32_t s);

typedef struct K___uint8_t_uint8_t_uint8_t_uint8_t_s
{
  uint8_t fst;
  uint8_t snd;
  uint8_t thd;
  uint8_t f3;
}
K___uint8_t_uint8_t_uint8_t_uint8_t;

K___uint8_t_uint8_t_uint8_t_uint8_t Ring_pop4__uint8_t(Ring_ringstruct__uint8_t r);

bool Ring_is_poppable__uint8_t(Ring_ringstruct__uint8_t r);

uint32_t
Reader_read(Ring_ringstruct__uint8_t r, uint32_t (*f)(uint8_t x0, uint8_t *x1, uint32_t x2));

#define __Reader_H_DEFINED
#endif
