/* 
  This file was generated by KreMLin <https://github.com/FStarLang/kremlin>
  KreMLin invocation: krml -verify -skip-compilation -bundle WasmSupport ../Writer.fst -I ../
  F* version: b55bb590
  KreMLin version: 2f843633
 */

#include "Reader.h"

Ring_ringstruct__uint8_t Reader_init(uint32_t s)
{
  return Ring_init__uint8_t((uint8_t)0U, s);
}

bool Ring_is_poppable__uint8_t(Ring_ringstruct__uint8_t r)
{
  uint32_t head1 = *r.headptr;
  uint32_t tail1 = *r.tailptr;
  uint32_t rsize = r.rsize;
  uint32_t space = Ring_get_current_size(head1, tail1, rsize);
  if (space > (uint32_t)0U)
    return true;
  else
    return false;
}

uint32_t Reader_read(Ring_ringstruct__uint8_t r)
{
  uint8_t header = Ring_pop__uint8_t(r);
  Prims_int
  len =
    FStar_UInt_logand((krml_checked_int_t)8,
      FStar_UInt8_v(header),
      FStar_UInt_max_int((krml_checked_int_t)8));
  bool canpop = Ring_is_poppable__uint8_t(r);
  if (canpop)
  {
    uint8_t m = Ring_pop__uint8_t(r);
    uint8_t *mptr = KRML_HOST_MALLOC(sizeof (uint8_t));
    mptr[0U] = m;
    return (uint32_t)1U;
  }
  else
    return (uint32_t)0U;
}

