/* 
  This file was generated by KreMLin <https://github.com/FStarLang/kremlin>
  KreMLin invocation: krml -verify -skip-compilation -bundle WasmSupport ../Writer.fst -I ../
  F* version: b55bb590
  KreMLin version: 2f843633
 */

#include "Ring.h"

bool Ring_is_rb_full(uint32_t rsize, uint32_t head1, uint32_t tail1)
{
  return head1 + (uint32_t)1U == tail1;
}

bool Ring_is_rb_empty(uint32_t rsize, uint32_t head1, uint32_t tail1)
{
  return head1 == tail1;
}

uint32_t Ring_incr_ht(uint32_t ht, uint32_t rsize)
{
  uint32_t ht_ = ht + (uint32_t)1U;
  if (ht_ == rsize)
    return (uint32_t)0U;
  else
    return ht_;
}

uint32_t Ring_get_current_size(uint32_t head1, uint32_t tail1, uint32_t rsize)
{
  if (head1 >= tail1)
    return head1 - tail1;
  else
    return rsize - (tail1 - head1);
}

uint32_t Ring_get_remaining_space(uint32_t head1, uint32_t tail1, uint32_t rsize)
{
  uint32_t c = Ring_get_current_size(head1, tail1, rsize);
  return rsize - c;
}

Ring_ringstruct__uint8_t Ring_init__uint8_t(uint8_t i, uint32_t s)
{
  KRML_CHECK_SIZE(sizeof (uint8_t), s);
  uint8_t *buf0 = KRML_HOST_MALLOC(sizeof (uint8_t) * s);
  for (uint32_t _i = 0U; _i < s; ++_i)
    buf0[_i] = i;
  uint32_t *buf1 = KRML_HOST_CALLOC((uint32_t)1U, sizeof (uint32_t));
  uint32_t *buf = KRML_HOST_CALLOC((uint32_t)1U, sizeof (uint32_t));
  return
    ((Ring_ringstruct__uint8_t){ .rbuf = buf0, .headptr = buf1, .tailptr = buf, .rsize = s });
}

void Ring_push__uint8_t(Ring_ringstruct__uint8_t r, uint8_t v1)
{
  uint32_t rsize = r.rsize;
  uint32_t head1 = *r.headptr;
  *r.headptr = Ring_incr_ht(head1, rsize);
  r.rbuf[head1] = v1;
}

uint8_t Ring_pop__uint8_t(Ring_ringstruct__uint8_t r)
{
  uint32_t rsize = r.rsize;
  uint32_t tail1 = *r.tailptr;
  *r.tailptr = Ring_incr_ht(tail1, rsize);
  return r.rbuf[tail1];
}

void Ring_push2__uint8_t(Ring_ringstruct__uint8_t r, uint8_t v1, uint8_t v2)
{
  Ring_push__uint8_t(r, v1);
  Ring_push__uint8_t(r, v2);
}

uint8_t Ring_test_ringbuffer()
{
  uint32_t rlen = (uint32_t)32U;
  uint8_t rinit = (uint8_t)1U;
  Ring_ringstruct__uint8_t rb = Ring_init__uint8_t(rinit, rlen);
  Ring_push__uint8_t(rb, (uint8_t)3U);
  uint8_t uu____0 = Ring_pop__uint8_t(rb);
  Ring_push__uint8_t(rb, (uint8_t)4U);
  uint8_t v1 = Ring_pop__uint8_t(rb);
  Ring_push2__uint8_t(rb, (uint8_t)5U, (uint8_t)6U);
  return v1;
}

