/* 
  This file was generated by KreMLin <https://github.com/FStarLang/kremlin>
  KreMLin invocation: krml -verify -skip-linking ../Reader.fst -I ../
  F* version: b55bb590
  KreMLin version: 2f843633
 */

#include "kremlib.h"
#ifndef __WasmSupport_H
#define __WasmSupport_H




extern void WasmSupport_trap();

uint32_t WasmSupport_align_64(uint32_t x);

void WasmSupport_check_buffer_size(uint32_t s);

uint32_t WasmSupport_betole32(uint32_t x);

uint64_t WasmSupport_betole64(uint64_t x);

#define __WasmSupport_H_DEFINED
#endif
