/* 
  This file was generated by KreMLin <https://github.com/FStarLang/kremlin>
  KreMLin invocation: krml -verify -skip-compilation -bundle WasmSupport ../Writer.fst -I ../
  F* version: b55bb590
  KreMLin version: 2f843633
 */

#include "Writer.h"

void Writer_write(Ring_ringstruct__uint8_t r, uint8_t v1)
{
  Ring_push__uint8_t(r, v1);
}

