/* 
  This file was generated by KreMLin <https://github.com/FStarLang/kremlin>
  KreMLin invocation: krml -verify -skip-linking -bundle WasmSupport ../Ring.fst ../Reader.fst ../Writer.fst ../Misc.fst -I ../
  F* version: b55bb590
  KreMLin version: 2f843633
 */

#include "kremlib.h"
#ifndef __Writer_H
#define __Writer_H

#include "Ring.h"


void Writer_write(Ring_ringstruct__uint8_t r, uint8_t v1);

#define __Writer_H_DEFINED
#endif
